### ISSUE TITLE
CI server notifies us of every run's results

### ISSUE THREAD

**Issue by haval0** [soffan-group-25/ci-server#14]
> Property (core CI feature number 3 - notification): the CI server supports notification of CI results. At least one notification mechanism of the following list is implemented:
> 
> Commit status: the CI server sets the [commit status](https://help.github.com/articles/about-statuses/) on the repository ([REST API](https://developer.github.com/v3/repos/statuses/) for Github)
> Email: the CI server sends an email to the project member about the build result.
> Preparation: The students document in the README how notification has been implemented and unit-tested.
> 
> Assessment: The grader observes the status of the change made while assessing P2. Optionally, the grader may look at the implementation or the tests of this feature.

**Comment by haval0** [comment]
I suggest we use the commit status method, not email. If so, this issue is strongly related to #12

**Comment by haval0** [comment]
Fully solving this will depend on #28 and #7

**Comment by didrikmunther** [comment]
Solved by #56
