### ISSUE TITLE
CI server should add checks that are not required in the assignment

### ISSUE THREAD

**Issue by haval0** [soffan-group-25/ci-server#15]
#8 #9 #10  are examples of this. Seems like it could qualify as remarkable

**Comment by danielwis** [comment]
Having the server review PRs could be another non-required feature. A review can then be posted [like this](https://docs.github.com/en/rest/pulls/reviews?apiVersion=2022-11-28#submit-a-pull-request-review).

**Comment by didrikmunther** [comment]
Project already achieved remarkable.
