### ISSUE TITLE
Make sure all public classes and methods are documented

### ISSUE THREAD

**Issue by haval0** [soffan-group-25/ci-server#17]
> Property (SE): the program is properly documented
> 
> Assessment: The grader randomly opens application files (not test files) to check that all public classes and methods are well documented ([hints](http://www.monperrus.net/martin/how-to-write-good-API-documentation)). In addition, the grader checks that the corresponding API documentation has been generated in a browsable format (eg HTML when using Javadoc).

This could be manually inspected every time, and added to the CONTRIBUTING.md checklist. Alternatively, it might be possible to have the CI server check that every class and method has valid Javadoc connected to it.

**Comment by didrikmunther** [comment]
Resolved
