### ISSUE TITLE
Establish clear descriptions of events, payloads and handling

### ISSUE THREAD

**Issue by danielwis** [soffan-group-25/ci-server#20]
As a group, we should establish clear mappings of events (e.g. new commit) to HTTP POST-payloads (e.g. commit hash, message, branch/belongs to open PR etc.), to what the CI server does upon receiving said payload. This will facilitate the implementation process by giving us concise guidelines and proper structure.

**Comment by danielwis** [comment]
Reading through the requirements[^1], it seems like we should use the [push](https://docs.github.com/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#push) hook for #5 and #7 (and thus also #14), as this will trigger every time something is pushed to the repository - no matter what branch. Of course, this will not interfere with you making several commits locally - it will only run once you push, at which point all of the commits you made since your last push will be included together in the payload (we can decide later if we want to run checks on all of them or only the last).

To find the relevant branch in the payload, we read the `ref` field and extract the branch name from `refs/heads/*` (`*` being the branch name). The push web hook will also fire when we push tags, and the `ref` field value will in this case start with `refs/tags/`, but this can most likely be ignored as we probably won't use any tags.

For setting the commit status (#14), we use the [REST API](https://docs.github.com/en/rest/commits/statuses?apiVersion=2022-11-28#create-a-commit-status), where we can provide the status, a URL that provides information about the build (like in the P+ related work), a custom description and more. An example CLI request is the following:
```
curl \
  -X POST \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: Bearer <YOUR-TOKEN>"\
  -H "X-GitHub-Api-Version: 2022-11-28" \
  https://api.github.com/repos/OWNER/REPO/statuses/SHA \
  -d '{"state":"success","target_url":"https://example.com/build/status","description":"The build succeeded!","context":"continuous-integration/jenkins"}'
```
i.e. some headers and a `json` object as payload.

[^1]: [Assignment 2](https://canvas.kth.se/courses/37918/assignments/235346): "[...] the CI server compiles the branch where the change has been made [...]"

**Comment by haval0** [comment]
I had the same thought at first regarding the push hook, but it seems that the [check_suite](https://docs.github.com/en/developers/apps/guides/creating-ci-tests-with-the-checks-api#checks-api-overview) event is the one intended to be used for this. I think we should mainly base our early work on the guide in that link. [This part](https://docs.github.com/en/developers/apps/guides/creating-ci-tests-with-the-checks-api#step-12-adding-event-handling) of the same guide shows how they implement the handling of the `check_suite` event.

**Comment by haval0** [comment]
> By default, a check suite is automatically created each time code is pushed to a repository. [^1]

[^1]: [Github Docs](https://docs.github.com/en/rest/checks/suites?apiVersion=2022-11-28#update-repository-preferences-for-check-suites). Cool markdown feature, thanks for demonstrating @danielwis

**Comment by haval0** [comment]
[This is where](https://docs.github.com/en/developers/apps/guides/creating-ci-tests-with-the-checks-api#step-25-updating-the-check-run-with-ci-test-results) the guide describes answering from our server back to GitHub

**Comment by haval0** [comment]
[General information about the check_suite event](https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#check_suite)
