### ISSUE TITLE
CI server should check that commits start with one of our valid prefixes

### ISSUE THREAD

**Issue by haval0** [soffan-group-25/ci-server#9]
"feat", "fix", "doc", or "refactor"

**Comment by haval0** [comment]
This might be done by checking for https://docs.github.com/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#pull_request with action type `edited` or `opened`, to make sure that the pull request title and description are set up as a valid commit according to our requirements

**Comment by haval0** [comment]
Implementation of this is related to #10

**Comment by didrikmunther** [comment]
Out of scope.
